import numpy as np

exec(open("dirac_probe.py").read().split("np.set_printoptions")[0])


def envelope_dim(gens, n):
    # dim of the associative algebra generated by gens (n x n matrices) incl identity
    basis_vecs = [np.eye(n).ravel()]

    def add(M):
        A = np.array(basis_vecs + [M.ravel()])
        if np.linalg.matrix_rank(A, tol=1e-8) > len(basis_vecs):
            basis_vecs.append(M.ravel())
            return True
        return False

    mats = [np.eye(n)]
    frontier = [np.eye(n)]
    for g in gens:
        if add(g):
            mats.append(g)
            frontier.append(g)
    while frontier and len(basis_vecs) < n * n:
        new = []
        for M in frontier:
            for g in gens:
                P = M @ g
                if add(P):
                    new.append(P)
        frontier = new
    return len(basis_vecs)


for n, name in [(4, "H"), (8, "O"), (16, "S")]:
    E = basis(n)
    gens = [L(E[a], n) for a in range(1, n)]
    print(name, "dim <L_a> =", envelope_dim(gens, n), " (full End =", n * n, ")")
# delta(s) range over random s in Im S, and zero-divisor endpoint
rng = np.random.default_rng(1)
ds = []
for _ in range(2000):
    r = rng.normal(size=16)
    r[0] = 0
    r /= np.linalg.norm(r)
    w = np.sort(np.linalg.eigvalsh(-(L(r, 16) @ L(r, 16))))
    ds.append(1 - w[0])
print("delta(s) over random unit s in Im S: min %.4f max %.4f" % (min(ds), max(ds)))
# an explicit zero-divisor direction: s = (e1 + e10)/sqrt2 (standard sedenion ZD pair)
E = basis(16)
s = (E[1] + E[10]) / np.sqrt(2)
w = np.sort(np.linalg.eigvalsh(-(L(s, 16) @ L(s, 16))))
print("s=(e1+e10)/√2 spectrum of -L_s^2:", np.round(w, 4))
# s inside an octonion subalgebra (first 8 coords): delta should be 0
s = rng.normal(size=16)
s[0] = 0
s[8:] = 0
s /= np.linalg.norm(s)
w = np.linalg.eigvalsh(-(L(s, 16) @ L(s, 16)))
print("s in O-subalgebra: spectrum", np.round(np.unique(np.round(w, 6)), 4))
