"""#473 AC1 rounds 13–15 (2026-09-05) — what the algebra's operations do with an UNFORCED second element.

Prop 16 (PR #631 / #634) covers one element (trivial) and the forced pair (s, ℓ) (quaternion subalgebra,
only ±ℓ reachable). Round 13's tempting generalisation — "the algebra's operations on any state generate
only H-space substructures (Adams' theorem in algebraic dress)" — is FALSE; this script is the evidence:

  (1) two generic imaginary units s, t generate a NON-associative subalgebra (dimension grows with word
      length; associator ~0.3–0.5, seed-dependent), not an H-space; the pair (s, ℓ) generates dim 4 with associator 0;
  (2) algebraic maps built from a state x and a generic unforced t (x·t, t·x, [x,t]) are not of finite
      order and drive every start to the ZERO-DIVISOR RIDGE V = 1 (the landscape maximum), not to the
      vacuum; (x+t)/‖·‖ attracts to t; x·(x·t) leaves Im𝕊.
  Several independent t are tested (round-15 condition (2) asked for more than one).
Runtime ≈ 4 min under `run-bounded 2G 600` (5 t × 40 starts × 120 iterations). Round-4 confirmer: the (2) maps are LINEAR (R_t, L_t, ad_t; skew for
imaginary t); normalised iteration is power iteration onto the top-singular plane (on V = 1), then period 2 up to
sign — 120 iterations are needed for the period test to settle (at 60 the residual ≈ (σ₅/σ₁)⁶⁰ straddles 1e-8).
Section (3) prints the mechanism: skewness, Σσ² = 16·N(t), top-plane V, and R_ℓ orthogonal.
Numerical flashlight only.
"""

import itertools
import os

import numpy as np

os.chdir(
    os.path.dirname(os.path.abspath(__file__))
)  # exec() below is cwd-relative; run from anywhere

exec(open("dirac_probe.py").read().split("def spec")[0])  # cd_mul
exec(open("flow_big.py").read().split("# --- FD check")[0])  # omul, V

rng = np.random.default_rng(31)
e = np.eye(16)


def nz(v):
    return v / np.linalg.norm(v)


def Vs(s):
    return V(np.concatenate([[0.0], s[1:8]])[None, :], s[8:][None, :])[0]


def rand_imag():
    s = rng.normal(size=16)
    s[0] = 0
    return nz(s)


def assoc(x, y, z):
    return cd_mul(cd_mul(x, y), z) - cd_mul(x, cd_mul(y, z))


def closure_dim(gens, maxlen):
    words = {1: [e[0]] + list(gens)}
    allv = list(words[1])
    for L in range(2, maxlen + 1):
        words[L] = [
            cd_mul(a, b) for i in range(1, L) for a in words[i] for b in words[L - i]
        ]
        allv += words[L]
    return np.linalg.matrix_rank(np.array(allv), 1e-8)


print("(1) subalgebra generated by two elements (words of length ≤ 4, ≤ 5):")
for k in range(3):
    s, t = rand_imag(), rand_imag()
    a = max(
        np.abs(assoc(x, y, z)).max()
        for x, y, z in itertools.product([s, t, cd_mul(s, t)], repeat=3)
    )
    print(
        f"    generic (s,t): dim {closure_dim([s,t],4)} / {closure_dim([s,t],5)}   max associator {a:.2f}"
    )
s = rand_imag()
a = max(
    np.abs(assoc(x, y, z)).max()
    for x, y, z in itertools.product([s, e[8], cd_mul(s, e[8])], repeat=3)
)
print(
    f"    forced (s,ℓ):  dim {closure_dim([s,e[8]],4)} / {closure_dim([s,e[8]],5)}   max associator {a:.1e}"
)

print(
    "(2) maps from (x, t), t generic unforced; 5 independent t, 40 starts each, 120 iterations:"
)
for name, mk in {
    "x·t": lambda t: (lambda x: nz(cd_mul(x, t))),
    "t·x": lambda t: (lambda x: nz(cd_mul(t, x))),
    "[x,t]": lambda t: (lambda x: nz(cd_mul(x, t) - cd_mul(t, x))),
    "x·(x·t)": lambda t: (lambda x: nz(cd_mul(x, cd_mul(x, t)))),
    "(x+t)/‖·‖": lambda t: (lambda x: nz(x + t)),
}.items():
    rows = []
    for _ in range(5):
        t = rand_imag()
        f = mk(t)
        ends, leaves, per = [], 0, []
        for _ in range(40):
            x = rand_imag()
            traj = [x]
            for _ in range(120):
                x = f(x)
                traj.append(x)
            leaves += abs(traj[-1][0]) > 1e-9
            p = None
            for k in range(1, 7):
                if (
                    min(
                        np.abs(traj[-1] - traj[-1 - k]).max(),
                        np.abs(traj[-1] + traj[-1 - k]).max(),
                    )
                    < 1e-8
                ):
                    p = k
                    break
            per.append(p)
            ends.append(traj[-1])
        ends = np.array(ends)
        rows.append(
            (
                leaves,
                np.mean([Vs(v) for v in ends]),
                np.mean([np.abs(a - b).max() for a in ends[:15] for b in ends[:15]]),
                sum(p is None for p in per),
            )
        )
    lv = [r[0] for r in rows]
    mv = [r[1] for r in rows]
    sp = [r[2] for r in rows]
    nf = [r[3] for r in rows]
    print(
        f"    {name:10s} leaves Im {min(lv)}–{max(lv)}/40 | mean V at end {min(mv):.3f}–{max(mv):.3f} | endpoint spread {min(sp):.2f}–{max(sp):.2f} | not finite-order(≤6) {min(nf)}–{max(nf)}/40"
    )
print("    (V = 1 is the zero-divisor ridge, the landscape maximum; V = 0 the vacuum)")

print(
    "(3) mechanism: x ↦ x·t is the linear map R_t (matrix on coordinates); top-σ subspace is 4-dim (an S³ on the sphere)"
)
for _ in range(3):
    t = rand_imag()
    Rt = np.array([cd_mul(e[k], t) for k in range(16)]).T
    sv = np.linalg.svd(Rt, compute_uv=False)
    _, _, Wt = np.linalg.svd(Rt)
    top = Wt[:4]
    vtop = np.mean([Vs(nz(top.T @ rng.normal(size=4))) for _ in range(5)])
    print(
        f"    skew |R+Rᵀ|max {np.abs(Rt + Rt.T).max():.1e} | σmax {sv[0]:.3f} (mult {int(np.sum(np.isclose(sv, sv[0], atol=1e-9)))}) σmin {sv[-1]:.3f} | Σσ² {np.sum(sv**2):.3f} = 16·N(t) | V on top plane {vtop:.6f}"
    )
Rl = np.array([cd_mul(e[k], e[8]) for k in range(16)]).T
print(
    f"    R_ℓ orthogonal (all σ = 1): {np.allclose(np.linalg.svd(Rl, compute_uv=False), 1)}  → no transient; NB this holds for every t in 𝕆 ∪ 𝕆ℓ (norm multiplicative there) — what singles out ℓ is [x,x,ℓ] = 0"
)
