"""RUNNER-SIDE CHECK (not a committed script): the hosted-set intersection claim.
Gemini R1 claim: for generic universes, U1.hosted inter U2.hosted = span{1, ell}.
We compute (i) the subalgebra generated by {1, s, ell} numerically, (ii) pairwise intersection dims,
(iii) the same-direction (u1 = u2, different (alpha,gamma,b0)) case, (iv) the pole case.
"""

import numpy as np, sys, os

sys.path.insert(
    0,
    "/home/prime/Documents/QBP/.claude/worktrees/probe-encode-bundle/analysis/473-dirac-probe",
)
from dirac_probe import cd_mul

N = 16


def e(i):
    v = np.zeros(N)
    v[i] = 1.0
    return v


ELL = e(8)


def vacuum(u, alpha, gamma, b0):
    s = np.zeros(N)
    s[:8] = alpha * u
    s[8] = b0
    s[8:] += gamma * u
    return s


def rand_crystal(rng, u=None):
    if u is None:
        u = rng.normal(size=8)
        u[0] = 0
        u /= np.linalg.norm(u)
    p = rng.normal(size=3)
    p /= np.linalg.norm(p)
    return vacuum(u, *p), u


def gen_subalgebra(gens, tol=1e-9):
    """closure of span(gens) under multiplication"""
    B = np.array(gens, dtype=float)
    B = orth(B, tol)
    for _ in range(12):
        prods = [cd_mul(x, y) for x in B for y in B]
        B2 = orth(np.vstack([B, np.array(prods)]), tol)
        if B2.shape[0] == B.shape[0]:
            return B
        B = B2
    return B


def orth(M, tol=1e-9):
    U, S, Vt = np.linalg.svd(np.array(M, dtype=float), full_matrices=False)
    r = int((S > tol * max(1.0, S[0])).sum())
    return Vt[:r]


def inter_dim(A, B, tol=1e-8):
    """dim of intersection of rowspaces"""
    # via SVD of the projection: dim(A)+dim(B)-dim(A+B)
    dA, dB = A.shape[0], B.shape[0]
    dAB = orth(np.vstack([A, B]), tol).shape[0]
    return dA + dB - dAB


rng = np.random.default_rng(1919)
# (i) dim of the generated hosted set
dims = []
for _ in range(30):
    s, u = rand_crystal(rng)
    H = gen_subalgebra([e(0), s, ELL])
    dims.append(H.shape[0])
print(
    "hosted = <1, s, ell> dims over 30 random crystals:",
    sorted(set(dims)),
    "counts",
    {d: dims.count(d) for d in set(dims)},
)

# compare with quatSpan span{1, ell, u, ell*u}
worst = 0.0
for _ in range(30):
    s, u = rand_crystal(rng)
    H = gen_subalgebra([e(0), s, ELL])
    ul = np.zeros(N)
    ul[:8] = u
    Q = orth([e(0), ELL, ul, cd_mul(ELL, ul)])
    d_union = orth(np.vstack([H, Q])).shape[0]
    worst = max(worst, abs(d_union - 4) + abs(H.shape[0] - 4) + abs(Q.shape[0] - 4))
print(
    "hosted == quatSpan{1,ell,u,ell u} for 30 generic crystals (0 = always equal):",
    worst,
)

# (ii) generic pairwise intersections
ids = []
for _ in range(50):
    s1, u1 = rand_crystal(rng)
    s2, u2 = rand_crystal(rng)
    H1 = gen_subalgebra([e(0), s1, ELL])
    H2 = gen_subalgebra([e(0), s2, ELL])
    ids.append(inter_dim(H1, H2))
print("generic pairs: intersection dims", {d: ids.count(d) for d in set(ids)})

# is the intersection exactly span{1, ell}?
s1, u1 = rand_crystal(rng)
s2, u2 = rand_crystal(rng)
H1 = gen_subalgebra([e(0), s1, ELL])
H2 = gen_subalgebra([e(0), s2, ELL])
C = orth([e(0), ELL])
print("span{1,ell} inside both:", inter_dim(C, H1) == 2 and inter_dim(C, H2) == 2)

# (iii) same direction u, different (alpha, gamma, b0)
same = []
for _ in range(30):
    u = rng.normal(size=8)
    u[0] = 0
    u /= np.linalg.norm(u)
    s1, _ = rand_crystal(rng, u)
    s2, _ = rand_crystal(rng, u)
    H1 = gen_subalgebra([e(0), s1, ELL])
    H2 = gen_subalgebra([e(0), s2, ELL])
    same.append((inter_dim(H1, H2), float(np.linalg.norm(s1 - s2))))
print(
    "same-u pairs (distinct crystals): intersection dims",
    {d: [x[0] for x in same].count(d) for d in set(x[0] for x in same)},
    "min |s1-s2| =",
    round(min(x[1] for x in same), 3),
)

# (iv) pole vs generic
pole = np.zeros(N)
pole[8] = 1.0
Hp = gen_subalgebra([e(0), pole, ELL])
s, u = rand_crystal(rng)
Hs = gen_subalgebra([e(0), s, ELL])
print(
    "pole hosted dim",
    Hp.shape[0],
    "; pole-vs-generic intersection dim",
    inter_dim(Hp, Hs),
    "; fraction of pole's hosted shared =",
    inter_dim(Hp, Hs) / Hp.shape[0],
)

# (v) does the shared C carry anything? unit sphere dims
print(
    "unit sphere of hosted H: S^3 (dim 3); unit sphere of shared C: S^1 (dim 1); codim in each universe = 2"
)
