name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Use this template to report bugs or unexpected behavior.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the bug
      placeholder: "Describe the bug in one or two sentences."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Describe what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Describe what actually happened."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      value: |
        - Python version:
        - OS:
        - Relevant dependencies:
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know the bug is fixed?
      value: |
        - [ ] Bug no longer reproducible
        - [ ] Regression test added
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      value: |
        - [ ] Fix implemented
        - [ ] Tests pass in CI
        - [ ] No new bugs introduced
        - [ ] PR merged to master
    validations:
      required: true
