/-
  QBP.Foundations.ArtinSpan
  =========================

  PR-C2c of the Artin strategy (`docs/foundations/artin-strategy-2026-06-06.md`,
  lemma L4).  **Multiplicative closure of the 4-dimensional span** and the
  `adjoin`-inclusion it yields:

      adjoin ℝ {x, y}  ≤  span ℝ {1, x, y, x*y}      (for x y : CDAlg ℝ 3 = 𝕆)

  i.e. the non-unital subalgebra generated by two octonions is contained in the
  4-dimensional ℝ-span of `{1, x, y, x*y}`.

  **Scope (truth-in-labelling).**  This file does **NOT** prove Artin's theorem.
  It proves the *span side* of the route: that `S := span ℝ {1,x,y,x*y}` is closed
  under multiplication, hence is a `NonUnitalSubalgebra` containing `{x,y}`, hence
  contains `adjoin ℝ {x,y}` by minimality (`NonUnitalAlgebra.adjoin_le`).  The
  associator-side reduction (`assoc` vanishes on `S`) lives in `ArtinCore`
  (`assoc_vanishes_on_span4`, PR-C2a); the final assembly into `octonion_artin`
  is C2d.  Nothing here claims associativity.

  **Route (strategy-ratified).**  Multiplicative closure = the 16 products of
  basis-of-span pairs `{1,x,y,x*y} × {1,x,y,x*y}` each reduce back into
  `span ℝ {1,x,y,x*y}`:

    * `1·b` and `a·1` (7 cells): immediate (`one_mul`/`mul_one`), land in the span.
    * `x·x`, `y·y` (2 cells): quadraticity `cdAlg_sq_eq` writes `x*x` as
      `(2 Re x)•x − N x•1 ∈ span{1,x}` ⊆ span.
    * `x·y` (1 cell): a generator, in the span by definition.
    * `y·x` (1 cell): **C2b's swap identity** `cdAlg_mul_add_swap` —
      `y*x = (x*y + y*x) − x*y`, and `x*y + y*x ∈ span{1,x,y}`, so `y*x ∈ span`.
    * `x·(x·y)`, `(x·y)·x`, `(x·y)·y`, `y·(x·y)`, `(x·y)·(x·y)` (5 cells):
      reduce by **alternativity** (`octonion_alternative`) + quadraticity / the
      swap identity, e.g. `x*(x*y) = (x*x)*y = ((2 Re x)•x − N x•1)*y ∈ span`.

  Closure is packaged through the **submodule** `span ℝ gen4`: we show each of the
  16 basis products lies in that submodule, then a bilinear span-induction
  (`bilinear_mem_span`) promotes closure to all of `span × span`.

  **Budget honesty (strategy §6-7).**  Zero `decide`, zero `native_decide`, zero
  `maxHeartbeats` bump (the bilinear/span machinery is all `rw`/`Submodule`
  algebra over the merged structure-constant lemmas).  Zero `sorry`, zero vacuous
  `True`.  `#print axioms` audit at the bottom — every result depends only on
  `{propext, Classical.choice, Quot.sound}`.

  **Instance finding (reported, not a `sorry`).**  `NonUnitalAlgebra.adjoin` and
  `adjoin_le` require `[NonUnitalNonAssocSemiring A] [Module R A]
  [IsScalarTower R A A] [SMulCommClass R A A]` (NO associativity — the
  associativity-requiring `NonUnitalSemiring` is only used by the *commutativity*
  lemmas later in that Mathlib file, which we do not touch).  `CDAlg R n` carried
  `AddCommGroup`, `Module R`, `One`, `Mul` but **not** the
  `NonUnitalNonAssocRing` / `IsScalarTower` / `SMulCommClass` instances.  We
  register them here (all laws are pre-existing merged theorems:
  `mul_add_left/right`, `mul_smul_left/right`, plus `zero_mul`/`mul_zero` proved
  from `mul_smul_*`).  This is a genuine missing-instance finding flagged in the
  report; it is *supplied*, not stubbed.
-/
import QBP.Foundations.ArtinCore
import QBP.Foundations.ArtinTrace
import Mathlib.Algebra.Algebra.NonUnitalSubalgebra

namespace QBP.Foundations.CDAlg

open scoped BigOperators

/-! ## 0. The missing algebra instances on `CDAlg R n`

`NonUnitalAlgebra.adjoin` / `adjoin_le` need `CDAlg R n` to be a
`NonUnitalNonAssocSemiring` (we give the stronger `NonUnitalNonAssocRing`, which
it is, since `CDAlg R n` is an `AddCommGroup`) together with the two scalar-action
compatibility classes `IsScalarTower R · ·` and `SMulCommClass R · ·`.  None of
these assume associativity of `*`. -/

section Instances

variable {R : Type*} [CommRing R] {n : ℕ}

/-- `x * 0 = 0` in `CDAlg R n` (the `MulZeroClass` part of
    `NonUnitalNonAssocRing`).  Direct from `mul_smul_right` with `r = 0`. -/
theorem cdAlg_mul_zero (x : CDAlg R n) : x * 0 = 0 := by
  have := mul_smul_right (0 : R) x 0
  simpa using this

/-- `0 * x = 0` in `CDAlg R n`.  Direct from `mul_smul_left` with `r = 0`. -/
theorem cdAlg_zero_mul (x : CDAlg R n) : 0 * x = 0 := by
  have := mul_smul_left (0 : R) 0 x
  simpa using this

/-- **Missing-instance finding (supplied).**  `CDAlg R n` is a
    `NonUnitalNonAssocRing` — additive abelian group, both distributive laws, and
    `0` absorbing — with **no** associativity assumed.  All four ring-axiom fields
    are pre-existing merged theorems. -/
instance instNonUnitalNonAssocRing : NonUnitalNonAssocRing (CDAlg R n) where
  left_distrib  := mul_add_right
  right_distrib := mul_add_left
  zero_mul      := cdAlg_zero_mul
  mul_zero      := cdAlg_mul_zero

/-- **Missing-instance finding (supplied).**  `IsScalarTower R (CDAlg R n) (CDAlg R n)`:
    `(r • a) • b = r • (a • b)`, where the `· • ·` between elements is `*`.  This is
    exactly `mul_smul_left` (note `a • b = a * b` by `smul_eq_mul`). -/
instance instIsScalarTower : IsScalarTower R (CDAlg R n) (CDAlg R n) where
  smul_assoc r a b := by
    simp only [smul_eq_mul]; exact mul_smul_left r a b

/-- **Missing-instance finding (supplied).**  `SMulCommClass R (CDAlg R n) (CDAlg R n)`:
    `r • (a • b) = a • (r • b)`, i.e. `r • (a*b) = a*(r•b)`.  This is the symmetric
    form of `mul_smul_right`. -/
instance instSMulCommClass : SMulCommClass R (CDAlg R n) (CDAlg R n) where
  smul_comm r a b := by
    simp only [smul_eq_mul]; exact (mul_smul_right r a b).symm

end Instances

/-! ## 1. Multiplication is bilinear (packaged as `IsBilinear`)

The four distributive/homogeneity laws bundled, so the bilinear span-closure lift
can consume them uniformly. -/

variable {R : Type*} [CommRing R] {n : ℕ}

/-! Multiplication on `CDAlg R n` is `R`-bilinear via the merged `mul_isBilinear`
(`CDBridge`); we reuse it directly rather than re-declaring. -/

/-! ## 2. Bilinear span-closure lift (reusable)

A bilinear map `T` whose value on every generator pair `(a,b)`, `a,b ∈ s`, lies in
`span R s`, sends all of `span R s × span R s` into `span R s`.  Two sequential
single-slot `Submodule.span_induction` applications (each slot's "lands-in-span"
set is a submodule, by bilinearity + `Submodule` closure under `+`, `•`, `0`). -/

/-- **Bilinear span-closure (reusable).**  If `T` is `R`-bilinear and `T a b ∈
    span R s` for all `a b ∈ s`, then `T x y ∈ span R s` for all `x y ∈ span R s`. -/
theorem bilinear_mem_span
    {T : CDAlg R n → CDAlg R n → CDAlg R n} (hT : IsBilinear T)
    {s : Set (CDAlg R n)}
    (hgen : ∀ a ∈ s, ∀ b ∈ s, T a b ∈ Submodule.span R s)
    {x y : CDAlg R n}
    (hx : x ∈ Submodule.span R s) (hy : y ∈ Submodule.span R s) :
    T x y ∈ Submodule.span R s := by
  induction hx using Submodule.span_induction with
  | mem a ha =>
    -- first slot a generator; induct on y
    induction hy using Submodule.span_induction with
    | mem b hb => exact hgen a ha b hb
    | zero =>
      have h0 : T a 0 = 0 := by
        have := hT.smul_right (0 : R) a 0; simpa using this
      rw [h0]; exact Submodule.zero_mem _
    | add y₁ y₂ _ _ ih₁ ih₂ =>
      rw [hT.add_right]; exact Submodule.add_mem _ ih₁ ih₂
    | smul r y₁ _ ih =>
      rw [hT.smul_right]; exact Submodule.smul_mem _ r ih
  | zero =>
    have h0 : T 0 y = 0 := by
      have := hT.smul_left (0 : R) 0 y; simpa using this
    rw [h0]; exact Submodule.zero_mem _
  | add x₁ x₂ _ _ ih₁ ih₂ =>
    rw [hT.add_left]; exact Submodule.add_mem _ ih₁ ih₂
  | smul r x₁ _ ih =>
    rw [hT.smul_left]; exact Submodule.smul_mem _ r ih

/-! ## 3. The 16 generator products land in `span ℝ {1, x, y, x*y}`

`gen4 x y = {1, x, y, x*y}` (from `ArtinCore`).  We show each of the four
generators, and each of the 16 products, lies in `span ℝ (gen4 x y)`. -/

section Span

variable (x y : CDAlg ℝ 3)

/-- `1 ∈ span ℝ {1,x,y,x*y}`. -/
theorem one_mem_span_gen4 : (1 : CDAlg ℝ 3) ∈ Submodule.span ℝ (gen4 x y) :=
  Submodule.subset_span (by simp [gen4])

/-- `x ∈ span ℝ {1,x,y,x*y}`. -/
theorem x_mem_span_gen4 : x ∈ Submodule.span ℝ (gen4 x y) :=
  Submodule.subset_span (by simp [gen4])

/-- `y ∈ span ℝ {1,x,y,x*y}`. -/
theorem y_mem_span_gen4 : y ∈ Submodule.span ℝ (gen4 x y) :=
  Submodule.subset_span (by simp [gen4])

/-- `x*y ∈ span ℝ {1,x,y,x*y}`. -/
theorem xy_mem_span_gen4 : x * y ∈ Submodule.span ℝ (gen4 x y) :=
  Submodule.subset_span (by simp [gen4])

/-- `x*x ∈ span` via quadraticity: `x*x = (2 Re x)•x − N x•1`, an ℝ-combination of
    `x` and `1`. -/
theorem xx_mem_span_gen4 : x * x ∈ Submodule.span ℝ (gen4 x y) := by
  rw [cdAlg_sq_eq]
  exact Submodule.sub_mem _
    (Submodule.smul_mem _ _ (x_mem_span_gen4 x y))
    (Submodule.smul_mem _ _ (one_mem_span_gen4 x y))

/-- `y*y ∈ span` via quadraticity. -/
theorem yy_mem_span_gen4 : y * y ∈ Submodule.span ℝ (gen4 x y) := by
  rw [cdAlg_sq_eq]
  exact Submodule.sub_mem _
    (Submodule.smul_mem _ _ (y_mem_span_gen4 x y))
    (Submodule.smul_mem _ _ (one_mem_span_gen4 x y))

/-- `y*x ∈ span` via **C2b's swap identity** `cdAlg_mul_add_swap`:
    `y*x = (x*y + y*x) − x*y`, and the trace form `x*y + y*x =
    (2 Re x)•y + (2 Re y)•x − (2⟨x,y⟩)•1 ∈ span{1,x,y}`, so subtracting the
    generator `x*y` keeps us in the span. -/
theorem yx_mem_span_gen4 : y * x ∈ Submodule.span ℝ (gen4 x y) := by
  have hrw : y * x = (x * y + y * x) - x * y := by abel
  rw [hrw, cdAlg_mul_add_swap]
  refine Submodule.sub_mem _ (Submodule.sub_mem _ (Submodule.add_mem _ ?_ ?_) ?_) ?_
  · exact Submodule.smul_mem _ _ (y_mem_span_gen4 x y)
  · exact Submodule.smul_mem _ _ (x_mem_span_gen4 x y)
  · exact Submodule.smul_mem _ _ (one_mem_span_gen4 x y)
  · exact xy_mem_span_gen4 x y

/-- `x*(x*y) ∈ span` via **left-alternativity**: `x*(x*y) = (x*x)*y`, then
    quadraticity on `x*x` turns this into `(2 Re x)•(x*y) − N x•y ∈ span{x*y, y}`. -/
theorem x_xy_mem_span_gen4 : x * (x * y) ∈ Submodule.span ℝ (gen4 x y) := by
  have hL : x * (x * y) = (x * x) * y := (octonion_alternative x y).1.symm
  rw [hL, cdAlg_sq_eq]
  -- ((2 Re x)•x − N x•1) * y = (2 Re x)•(x*y) − N x•(1*y) = (2 Re x)•(x*y) − N x•y
  rw [sub_mul, smul_mul_assoc, smul_mul_assoc, cdAlg_one_mul]
  exact Submodule.sub_mem _
    (Submodule.smul_mem _ _ (xy_mem_span_gen4 x y))
    (Submodule.smul_mem _ _ (y_mem_span_gen4 x y))

/-- `(x*y)*y ∈ span` via **right-alternativity**: `(x*y)*y = x*(y*y)`, then
    quadraticity on `y*y` turns this into `(2 Re y)•(x*y) − N y•x ∈ span{x*y, x}`. -/
theorem xy_y_mem_span_gen4 : (x * y) * y ∈ Submodule.span ℝ (gen4 x y) := by
  have hR : (x * y) * y = x * (y * y) := (octonion_alternative x y).2
  rw [hR, cdAlg_sq_eq]
  -- x * ((2 Re y)•y − N y•1) = (2 Re y)•(x*y) − N y•(x*1) = (2 Re y)•(x*y) − N y•x
  rw [mul_sub, mul_smul_comm, mul_smul_comm, cdAlg_mul_one]
  exact Submodule.sub_mem _
    (Submodule.smul_mem _ _ (xy_mem_span_gen4 x y))
    (Submodule.smul_mem _ _ (x_mem_span_gen4 x y))

/-- `(x*y)*x ∈ span`.  Swap identity on the pair `(x*y, x)`:
    `(x*y)*x = ((x*y)*x + x*(x*y)) − x*(x*y)`; the trace form lands in
    `span{1, x, x*y}`, and `x*(x*y) ∈ span` by `x_xy_mem_span_gen4`. -/
theorem xy_x_mem_span_gen4 : (x * y) * x ∈ Submodule.span ℝ (gen4 x y) := by
  have hrw : (x * y) * x = ((x * y) * x + x * (x * y)) - x * (x * y) := by abel
  rw [hrw, cdAlg_mul_add_swap]
  refine Submodule.sub_mem _ (Submodule.sub_mem _ (Submodule.add_mem _ ?_ ?_) ?_) ?_
  · exact Submodule.smul_mem _ _ (x_mem_span_gen4 x y)
  · exact Submodule.smul_mem _ _ (xy_mem_span_gen4 x y)
  · exact Submodule.smul_mem _ _ (one_mem_span_gen4 x y)
  · exact x_xy_mem_span_gen4 x y

/-- `y*(x*y) ∈ span`.  Swap identity on the pair `(y, x*y)`:
    `y*(x*y) = (y*(x*y) + (x*y)*y) − (x*y)*y`; the trace form lands in
    `span{1, y, x*y}`, and `(x*y)*y ∈ span` by `xy_y_mem_span_gen4`. -/
theorem y_xy_mem_span_gen4 : y * (x * y) ∈ Submodule.span ℝ (gen4 x y) := by
  have hrw : y * (x * y) = (y * (x * y) + (x * y) * y) - (x * y) * y := by abel
  rw [hrw, cdAlg_mul_add_swap]
  refine Submodule.sub_mem _ (Submodule.sub_mem _ (Submodule.add_mem _ ?_ ?_) ?_) ?_
  · exact Submodule.smul_mem _ _ (xy_mem_span_gen4 x y)
  · exact Submodule.smul_mem _ _ (y_mem_span_gen4 x y)
  · exact Submodule.smul_mem _ _ (one_mem_span_gen4 x y)
  · exact xy_y_mem_span_gen4 x y

/-- `(x*y)*(x*y) ∈ span` via quadraticity applied to the element `x*y`:
    `(x*y)*(x*y) = (2 Re (x*y))•(x*y) − N(x*y)•1 ∈ span{x*y, 1}`. -/
theorem xyxy_mem_span_gen4 : (x * y) * (x * y) ∈ Submodule.span ℝ (gen4 x y) := by
  rw [cdAlg_sq_eq]
  exact Submodule.sub_mem _
    (Submodule.smul_mem _ _ (xy_mem_span_gen4 x y))
    (Submodule.smul_mem _ _ (one_mem_span_gen4 x y))

/-! ## 4. The full 16-cell generator-product closure -/

/-- **All 16 generator products land in `span ℝ {1,x,y,x*y}`.**  For
    `a b ∈ gen4 x y`, `a * b ∈ span ℝ (gen4 x y)`.  Discharged cell-by-cell by the
    nine product lemmas above (`one_mul`/`mul_one` cells immediate; quadraticity;
    swap identity; alternativity). -/
theorem gen4_mul_mem_span (a : CDAlg ℝ 3) (ha : a ∈ gen4 x y)
    (b : CDAlg ℝ 3) (hb : b ∈ gen4 x y) :
    a * b ∈ Submodule.span ℝ (gen4 x y) := by
  simp only [gen4, Set.mem_insert_iff, Set.mem_singleton_iff] at ha hb
  -- Rewrite `a`,`b` to their values with `rw` (LHS→RHS only) so the section
  -- variables `x`,`y` are never eliminated from context (cf. ArtinCore's
  -- `assoc_gen4_*`); `subst` would substitute *away* `x`/`y` in cells like `b = x`.
  rcases ha with ha | ha | ha | ha <;> rcases hb with hb | hb | hb | hb <;>
    rw [ha, hb]
  -- a = 1
  · rw [cdAlg_one_mul]; exact one_mem_span_gen4 x y
  · rw [cdAlg_one_mul]; exact x_mem_span_gen4 x y
  · rw [cdAlg_one_mul]; exact y_mem_span_gen4 x y
  · rw [cdAlg_one_mul]; exact xy_mem_span_gen4 x y
  -- a = x
  · rw [cdAlg_mul_one]; exact x_mem_span_gen4 x y
  · exact xx_mem_span_gen4 x y
  · exact xy_mem_span_gen4 x y
  · exact x_xy_mem_span_gen4 x y
  -- a = y
  · rw [cdAlg_mul_one]; exact y_mem_span_gen4 x y
  · exact yx_mem_span_gen4 x y
  · exact yy_mem_span_gen4 x y
  · exact y_xy_mem_span_gen4 x y
  -- a = x*y
  · rw [cdAlg_mul_one]; exact xy_mem_span_gen4 x y
  · exact xy_x_mem_span_gen4 x y
  · exact xy_y_mem_span_gen4 x y
  · exact xyxy_mem_span_gen4 x y

/-! ## 5. Span multiplicative closure (L4) and the `adjoin` inclusion -/

/-- **L4 — `span4_mul_closed`.**  `S := span ℝ {1,x,y,x*y}` is closed under
    multiplication: for `u v ∈ S`, `u * v ∈ S`.  Promotes the 16-cell generator
    closure to the whole span via the bilinear span-closure lift
    (`bilinear_mem_span` + `mul_isBilinear`). -/
theorem span4_mul_closed
    {u v : CDAlg ℝ 3}
    (hu : u ∈ Submodule.span ℝ (gen4 x y)) (hv : v ∈ Submodule.span ℝ (gen4 x y)) :
    u * v ∈ Submodule.span ℝ (gen4 x y) :=
  bilinear_mem_span mul_isBilinear (gen4_mul_mem_span x y) hu hv

/-- The non-unital subalgebra of `CDAlg ℝ 3` carried by `span ℝ {1, x, y, x*y}`.
    Its `Submodule` part is the span; `mul_mem'` is `span4_mul_closed`. -/
def span4Subalgebra : NonUnitalSubalgebra ℝ (CDAlg ℝ 3) where
  toSubmodule := Submodule.span ℝ (gen4 x y)
  mul_mem' := span4_mul_closed x y

@[simp] theorem mem_span4Subalgebra {z : CDAlg ℝ 3} :
    z ∈ span4Subalgebra x y ↔ z ∈ Submodule.span ℝ (gen4 x y) := Iff.rfl

/-- **`adjoin_le` inclusion (the C2c deliverable).**  The non-unital subalgebra
    generated by `{x, y}` is contained in the 4-dimensional span `{1,x,y,x*y}`:

        adjoin ℝ {x, y}  ≤  span ℝ {1, x, y, x*y}.

    Proof: `span4Subalgebra` is a `NonUnitalSubalgebra` containing `{x, y}`
    (both generators of `gen4`), so by minimality of `adjoin`
    (`NonUnitalAlgebra.adjoin_le`) it contains `adjoin ℝ {x, y}`.

    **Truth-in-labelling (W1).**  The 4-dimensionality of the bound is a
    *consequence* of the explicit 16-cell structure-constant closure
    (`gen4_mul_mem_span`), NOT an appeal to the Hurwitz / composition-algebra
    classification.  No "2-generated subalgebra is ℝ/ℂ/ℍ" theorem is used. -/
theorem adjoin_pair_le_span4 :
    NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3)) ≤ span4Subalgebra x y := by
  apply NonUnitalAlgebra.adjoin_le
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with hz | hz <;> rw [hz]
  · exact x_mem_span_gen4 x y
  · exact y_mem_span_gen4 x y

/-- **C2c payload (membership form).**  Every element of the non-unital subalgebra
    generated by `{x, y}` lies in `span ℝ {1, x, y, x*y}`.  Convenience corollary
    of `adjoin_pair_le_span4`, in the shape C2d will consume to feed
    `assoc_vanishes_on_span4`. -/
theorem mem_span4_of_mem_adjoin {z : CDAlg ℝ 3}
    (hz : z ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3))) :
    z ∈ Submodule.span ℝ (gen4 x y) :=
  adjoin_pair_le_span4 x y hz

end Span

/-! ## 6. Completeness audit — `#print axioms`

Every theorem must depend only on `{propext, Classical.choice, Quot.sound}`.
The L4 deliverable is `span4_mul_closed`; the adjoin inclusion is
`adjoin_pair_le_span4`. -/

#print axioms cdAlg_mul_zero
#print axioms cdAlg_zero_mul
#print axioms bilinear_mem_span
#print axioms xx_mem_span_gen4
#print axioms yx_mem_span_gen4
#print axioms x_xy_mem_span_gen4
#print axioms xy_y_mem_span_gen4
#print axioms xy_x_mem_span_gen4
#print axioms y_xy_mem_span_gen4
#print axioms xyxy_mem_span_gen4
#print axioms gen4_mul_mem_span
#print axioms span4_mul_closed
#print axioms adjoin_pair_le_span4
#print axioms mem_span4_of_mem_adjoin

end QBP.Foundations.CDAlg
