/-
  QBP.Foundations.Artin
  =====================

  PR-C2d of the Artin strategy (`docs/foundations/artin-strategy-2026-06-06.md`,
  lemma L5, the C2d row).  **The full Artin theorem at 𝕆 = `CDAlg ℝ 3`.**

  This is the final assembly chunk that closes **#474 AC2 (Artin)**.  All inputs
  are merged kernel theorems:

    * `ArtinCore.assoc_vanishes_on_span4` (C2a) — the associator `assoc`
      vanishes on the whole module span `span ℝ {1, x, y, x*y}`, proven by the
      complete 64-generator-triple discharge (L1 + alternativity-diag + L2
      survivor + flexibility) lifted through trilinearity.  **No** appeal to the
      Hurwitz / composition-algebra classification.
    * `ArtinSpan.mem_span4_of_mem_adjoin` (C2c) — every element of the genuine
      non-unital generated subalgebra `NonUnitalAlgebra.adjoin ℝ {x, y}` lies in
      `span ℝ {1, x, y, x*y}`, proven by direct 16-cell structure-constant
      multiplicative closure of the span (quadraticity + swap identity +
      alternativity) and `NonUnitalAlgebra.adjoin_le` minimality.  **No** appeal
      to classification.

  The assembly is three lines of theory: push all three of `u, v, w` from
  adjoin-membership to span4-membership (C2c), conclude `assoc u v w = 0` (C2a),
  and unfold `assoc u v w = (u*v)*w − u*(v*w)` to read off `(u*v)*w = u*(v*w)`.

  **Truth-in-labelling (Wilson W1 — gate item).**  This file genuinely proves
  Artin's theorem at the octonions: *every subalgebra of `CDAlg ℝ 3` generated by
  two elements is associative.*  The Lean object `NonUnitalAlgebra.adjoin ℝ {x,y}`
  IS the generated non-unital subalgebra (not a hand-picked monomial list), and
  the conclusion `(u*v)*w = u*(v*w)` for ALL `u v w` in it IS associativity of
  that subalgebra.  This is the FULL Artin theorem instantiated at the matrix
  cell, NOT a weakening.

  The proof is derived **from alternativity** (via the merged
  `octonion_alternative` / polarized-alternativity / flexibility lemmas), through
  the span route — there is **NO** appeal to Hurwitz's theorem, to the
  classification of composition algebras, or to "every 2-generated subalgebra of a
  composition algebra is ℝ/ℂ/ℍ".  The 4-dimensionality of `span {1,x,y,x*y}` is a
  *consequence* of the explicit structure-constant closure computation, never a
  premise.  See the W1 resolution in the strategy doc §3 and the docstrings of
  `ArtinSpan.adjoin_pair_le_span4` / `ArtinCore.assoc_gen4_zero`.

  **Budget honesty (strategy §6-7).**  Zero `sorry`, zero `native_decide`, zero
  `decide`, zero vacuous `True`, zero `maxHeartbeats` bump.  The assembly is pure
  `rw` / membership composition over the merged lemmas.  `#print axioms` audit at
  the bottom: `octonion_artin` (and the `assoc`-form / matrix-cell corollaries)
  depend only on `{propext, Classical.choice, Quot.sound}`.
-/
import QBP.Foundations.ArtinCore
import QBP.Foundations.ArtinSpan

namespace QBP.Foundations.CDAlg

open scoped BigOperators

/-! ## The full Artin theorem at 𝕆 = `CDAlg ℝ 3` -/

/-- **Artin's theorem at 𝕆.**  Every subalgebra of `CDAlg ℝ 3` generated by two
    elements is associative: for all generators `x y` and all `u v w` in the
    non-unital generated subalgebra `NonUnitalAlgebra.adjoin ℝ {x, y}`, the product
    re-associates, `(u * v) * w = u * (v * w)`.

    **This IS the full Artin theorem at the octonions** (beekeeper-ruled scope),
    not a weakening: `NonUnitalAlgebra.adjoin ℝ {x, y}` is the genuine generated
    non-unital subalgebra, and `(u*v)*w = u*(v*w)` for every triple in it is
    exactly associativity of that subalgebra.

    **Proof route (truth-in-labelling, W1).**
    `adjoin ℝ {x, y} ≤ span ℝ {1, x, y, x*y}` (`mem_span4_of_mem_adjoin`, C2c —
    closure of the 4-dim span proven by direct structure-constant reduction, NO
    appeal to the Hurwitz classification), then `assoc` vanishes on that span
    (`assoc_vanishes_on_span4`, C2a — 64-generator-triple discharge from L1 +
    alternativity + the survivor `assoc x y (x*y) = 0` + flexibility, lifted by
    trilinearity).  `assoc u v w = (u*v)*w − u*(v*w) = 0` then re-associates.
    Derived from **alternativity**, not from Hurwitz / classification. -/
theorem octonion_artin
    (x y : CDAlg ℝ 3)
    {u v w : CDAlg ℝ 3}
    (hu : u ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3)))
    (hv : v ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3)))
    (hw : w ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3))) :
    (u * v) * w = u * (v * w) := by
  -- Push each of u,v,w from adjoin-membership to span4-membership (C2c).
  have hu' : u ∈ Submodule.span ℝ (gen4 x y) := mem_span4_of_mem_adjoin x y hu
  have hv' : v ∈ Submodule.span ℝ (gen4 x y) := mem_span4_of_mem_adjoin x y hv
  have hw' : w ∈ Submodule.span ℝ (gen4 x y) := mem_span4_of_mem_adjoin x y hw
  -- The associator vanishes on the span (C2a).
  have hassoc : assoc u v w = 0 := assoc_vanishes_on_span4 x y hu' hv' hw'
  -- assoc u v w = (u*v)*w − u*(v*w); vanishing gives the re-association.
  rw [assoc, sub_eq_zero] at hassoc
  exact hassoc

/-- **Artin's theorem at 𝕆, associator form.**  The associator `assoc u v w`
    (`= (u*v)*w − u*(v*w)`) vanishes for all `u v w` in the non-unital subalgebra
    generated by two octonions `x y`.  Definitionally equivalent to
    `octonion_artin`; provided in the `assoc = 0` shape the foundation matrix index
    (`#check`) and downstream consumers reference. -/
theorem octonion_artin_assoc
    (x y : CDAlg ℝ 3)
    {u v w : CDAlg ℝ 3}
    (hu : u ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3)))
    (hv : v ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3)))
    (hw : w ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3))) :
    assoc u v w = 0 := by
  rw [assoc, sub_eq_zero]
  exact octonion_artin x y hu hv hw

/-- **Matrix-cell-facing corollary (PR-G index).**  The two generators `x, y`
    themselves, together with their product `x * y`, re-associate inside the
    generated subalgebra — the canonical "two octonions associate" witness.  A
    direct specialization of `octonion_artin` to the self-membership of `x` and
    `y` (`NonUnitalAlgebra.subset_adjoin`).  Useful as the smallest concrete
    instance the matrix index can `#check` without carrying adjoin hypotheses. -/
theorem octonion_artin_gen
    (x y : CDAlg ℝ 3) :
    (x * y) * x = x * (y * x) := by
  have hx : x ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3)) :=
    NonUnitalAlgebra.subset_adjoin ℝ (by simp)
  have hy : y ∈ NonUnitalAlgebra.adjoin ℝ ({x, y} : Set (CDAlg ℝ 3)) :=
    NonUnitalAlgebra.subset_adjoin ℝ (by simp)
  exact octonion_artin x y hx hy hx

/-! ## Completeness audit — `#print axioms`

The deliverable `octonion_artin` (and the `assoc`-form / generator corollaries)
must depend only on `{propext, Classical.choice, Quot.sound}`.  This closes
**#474 AC2 (Artin)**. -/

#print axioms octonion_artin
#print axioms octonion_artin_assoc
#print axioms octonion_artin_gen

end QBP.Foundations.CDAlg
