#!/usr/bin/env python3
"""
Seed the QBP Knowledge Base with foundational content.

This script populates the hypergraph with core QBP concepts, claims,
and their relationships based on completed experiments and proofs.

Usage:
    python scripts/seed_qbp_knowledge.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from qbp_knowledge import QBPKnowledge


def seed_knowledge_base(db_path: str = "knowledge/qbp.hgdb"):
    """Seed the knowledge base with core QBP content."""

    kb = QBPKnowledge(db_path)

    print("Seeding QBP Knowledge Base...")
    print()

    # =========================================================================
    # SOURCES
    # =========================================================================
    print("Adding sources...")

    kb.add_source("qm-griffiths", "Introduction to Quantum Mechanics",
                  category="book",
                  authors=["David J. Griffiths"],
                  tags=["quantum-mechanics", "textbook", "reference"])

    kb.add_source("hamilton-1843", "On Quaternions",
                  category="paper",
                  authors=["William Rowan Hamilton"],
                  date="1843",
                  tags=["quaternions", "mathematics", "foundational"])

    kb.add_source("qbp-design-rationale", "QBP Design Rationale",
                  category="internal",
                  url="paper/DESIGN_RATIONALE.md",
                  tags=["qbp", "design", "internal"])

    # =========================================================================
    # CONCEPTS
    # =========================================================================
    print("Adding concepts...")

    kb.add_concept("quaternion-state", "Quaternion State Representation",
                   definition="Pure unit quaternion ψ with Re(ψ)=0, |ψ|=1 representing a spin-1/2 quantum state",
                   formal_definition="ψ ∈ ℍ : Re(ψ) = 0, |ψ|² = 1",
                   tags=["quaternions", "quantum-mechanics", "foundations", "axiom-1"])

    kb.add_concept("quaternion-observable", "Quaternion Observable Representation",
                   definition="Pure quaternion O representing a physical observable (measurement axis)",
                   formal_definition="O ∈ ℍ : Re(O) = 0",
                   tags=["quaternions", "quantum-mechanics", "foundations", "axiom-2"])

    kb.add_concept("quaternion-evolution", "Quaternion Time Evolution",
                   definition="State evolution under Hamiltonian H: ψ(t) = exp(-Ht)·ψ(0)",
                   tags=["quaternions", "quantum-mechanics", "foundations", "axiom-3"])

    kb.add_concept("measurement-postulate", "QBP Measurement Postulate",
                   definition="Expectation value ⟨O⟩ = vec(ψ)·vec(O)/|vec(O)|, probabilities via Born rule",
                   tags=["quaternions", "quantum-mechanics", "measurement"])

    kb.add_concept("pauli-algebra", "Pauli Algebra",
                   definition="The algebra generated by Pauli matrices σ_x, σ_y, σ_z satisfying σ_i² = I",
                   formal_definition="{σ_x, σ_y, σ_z} with [σ_i, σ_j] = 2iε_ijk σ_k",
                   tags=["quantum-mechanics", "algebra", "foundations"])

    kb.add_concept("bloch-sphere", "Bloch Sphere",
                   definition="Geometric representation of qubit states as points on S²",
                   tags=["quantum-mechanics", "geometry", "visualization"])

    kb.add_concept("half-angle-formula", "Half-Angle Formula",
                   definition="Rotation quaternion q = cos(θ/2) + sin(θ/2)·n̂ for rotation by θ about axis n̂",
                   tags=["quaternions", "rotation", "spin", "su2"])

    kb.add_concept("su2-double-cover", "SU(2) Double Cover of SO(3)",
                   definition="SU(2) covers SO(3) twice: a 2π rotation gives -1, 4π needed to return to identity",
                   tags=["group-theory", "spin", "topology"])

    kb.add_concept("quaternion-pauli-isomorphism", "Quaternion-Pauli Isomorphism",
                   definition="The imaginary quaternions {i,j,k} are isomorphic to Pauli matrices {-iσ_x, -iσ_y, -iσ_z}",
                   tags=["quaternions", "quantum-mechanics", "algebra", "isomorphism"])

    # =========================================================================
    # CLAIMS
    # =========================================================================
    print("Adding claims...")

    kb.add_claim("cosine-squared-formula",
                 "P(+) = cos²(θ/2) for spin measurement at angle θ from preparation axis",
                 status="established",
                 confidence_tier=3,
                 context="Derived from QBP measurement postulate, verified by Lean proof and simulation",
                 tags=["measurement", "spin", "validated", "experiment-01b"])

    kb.add_claim("qbp-matches-qm-single",
                 "QBP predictions match standard QM exactly for single-particle spin-1/2 systems",
                 status="established",
                 confidence_tier=3,
                 context="Mathematically necessary due to quaternion-Pauli algebra isomorphism",
                 tags=["validation", "single-particle", "foundations"])

    kb.add_claim("stern-gerlach-50-50",
                 "Stern-Gerlach experiment on z-prepared state measured along x gives 50/50 split",
                 status="established",
                 confidence_tier=3,
                 context="Special case of cos²(θ/2) formula with θ=90°",
                 tags=["measurement", "spin", "validated", "experiment-01"])

    kb.add_claim("half-angle-from-su2",
                 "The half-angle in measurement formula arises from SU(2) being double cover of SO(3)",
                 status="established",
                 confidence_tier=3,
                 context="The θ/2 is not arbitrary but reflects spinor geometry",
                 tags=["foundations", "geometry", "spin"])

    # =========================================================================
    # HYPEREDGES
    # =========================================================================
    print("Adding hyperedges...")

    # Evidence chains
    kb.add_evidence_chain("claim:cosine-squared-formula",
                          ["proof:angledependent", "source:qm-griffiths", "source:qbp-design-rationale"],
                          confidence_tier=3,
                          description="Lean proof + QM textbook derivation + design docs")

    kb.add_evidence_chain("claim:qbp-matches-qm-single",
                          ["proof:sterngerlach", "proof:angledependent", "source:qbp-design-rationale"],
                          confidence_tier=3,
                          description="Both experiments match QM, explained by isomorphism")

    kb.add_evidence_chain("claim:stern-gerlach-50-50",
                          ["proof:sterngerlach", "source:qm-griffiths"],
                          confidence_tier=3,
                          description="Lean proof + textbook verification")

    # Proof links
    kb.add_proof_link("claim:cosine-squared-formula", "proof:angledependent",
                      theorem="measurement_probability_formula",
                      verification_status="verified")

    kb.add_proof_link("claim:stern-gerlach-50-50", "proof:sterngerlach",
                      theorem="stern_gerlach_probability",
                      verification_status="verified")

    # Equivalence classes
    kb.add_equivalence(
        ["concept:quaternion-state", "concept:pauli-algebra", "concept:bloch-sphere"],
        description="Isomorphic representations of spin-1/2 state space",
        isomorphism_proven=True
    )

    # Theory axioms
    kb.add_theory_axioms(
        ["concept:quaternion-state", "concept:quaternion-observable",
         "concept:quaternion-evolution", "concept:measurement-postulate"],
        theory="QBP",
        completeness="sufficient for single-particle spin-1/2"
    )

    # Research cluster
    kb.add_research_cluster(
        ["question:qbp-divergence", "concept:quaternion-pauli-isomorphism",
         "claim:qbp-matches-qm-single"],
        theme="Novel QBP Predictions",
        priority="high",
        target_sprint="0R"
    )

    # Emergence
    kb.add_hyperedge(
        ("concept:half-angle-formula", "concept:su2-double-cover", "concept:quaternion-state"),
        "emergence",
        {
            "emergent_property": "Spinor sign flip under 2π rotation",
            "physical_significance": "Distinguishes fermions from bosons"
        }
    )

    # =========================================================================
    # SAVE
    # =========================================================================
    kb.save()

    print()
    print(kb.summary())
    print()
    print("✓ Knowledge base seeded successfully")

    return kb


if __name__ == '__main__':
    seed_knowledge_base()
